return {
    -- {
    --     "akinsho/bufferline.nvim",
    --     lazy = false,
    --     version = "*",
    --     dependencies = "nvim-tree/nvim-web-devicons",
    --     cmd = "BufferLine",
    --     keys = {
    --         { "<leader>bj", "<cmd>BufferLinePick<cr>", desc = "BufferLinePick" },
    --         { "<leader>be", "<cmd>BufferLinePickClose<cr>", desc = "BufferLinePickClose" },
    --         { "<leader>bn", "<cmd>BufferLineCycleNext<cr>", desc = "BufferLineCycleNext" },
    --         { "<leader>bN", "<cmd>BufferLineCyclePrev<cr>", desc = "BufferLineCyclePrev" },
    --         { "<leader>bco", "<cmd>BufferLineCloseOthers<cr>", desc = "BufferLineCloseOthers" },
    --         { "<leader>bch", "<cmd>BufferLineCloseLeft<cr>", desc = "BufferLineCloseLeft" },
    --         { "<leader>bcl", "<cmd>BufferLineCloseRight<cr>", desc = "BufferLineCloseRight" },
    --     },
    --     config = function()
    --         require("bufferline").setup {}
    --     end,
    -- },
}
